name: Release

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .parcel-cache
          key: ${{ runner.os }}-node${{ matrix.node }}-parcel
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: latest
          cache: npm
      - run: npm ci --include=dev
      - run: npm publish
        if: ${{ !github.event.release.prerelease }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm publish --tag next
        if: ${{ github.event.release.prerelease }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
